---
- hosts: kode
  tasks:
    - name: Update apt-get repo and cache
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install packages
      apt: name={{ item }} state=latest
      with_items:
        - curl
        - wget
        - htop
      sudo: yes